"""initial

Revision ID: 29dad6557936
Revises: 
Create Date: 2026-04-10 15:27:40.210461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29dad6557936'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions_families',
    sa.Column('family', sa.Text(), nullable=False),
    sa.Column('extraction_prompt', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('family')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('oauth_provider', sa.String(), nullable=False),
    sa.Column('oauth_provider_uid', sa.String(), nullable=False),
    sa.Column('phone_hash', sa.String(), nullable=True),
    sa.Column('device_hash', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True, precision=0), nullable=True),
    sa.Column('user_a_availability_window', postgresql.DATEMULTIRANGE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_provider_uid')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_a_id', sa.UUID(), nullable=False),
    sa.Column('user_b_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_method', sa.Enum('COSINE', 'LTR', 'LIGHTFM', name='scoremethod'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
    sa.CheckConstraint('-1.0 <= score AND score <= 1.0'),
    sa.CheckConstraint('user_a_id < user_b_id', name='ck_user_order_matches'),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_pairs_match', 'matches', ['user_a_id', 'user_b_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_family_id', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_family_id'], ['questions_families.family'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_a_id', sa.UUID(), nullable=False),
    sa.Column('user_b_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scheduled_starting_time', postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
    sa.Column('actual_starting_time', postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True, precision=0), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('user_a_message_count', sa.Integer(), nullable=True),
    sa.Column('user_b_message_count', sa.Integer(), nullable=True),
    sa.CheckConstraint('user_a_id < user_b_id', name='ck_session_user_order'),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_pair', 'sessions', ['user_a_id', 'user_b_id'], unique=True, postgresql_where="status = 'active'")
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_subscription_id', sa.String(), nullable=True),
    sa.Column('start', postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
    sa.Column('end', postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_answers_author_created_submitted_at_desc', 'answers', ['user_id', sa.literal_column('submitted_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_answers_author_created_submitted_at_desc', table_name='answers')
    op.drop_table('answers')
    op.drop_table('subscriptions')
    op.drop_index('idx_sessions_pair', table_name='sessions', postgresql_where="status = 'active'")
    op.drop_table('sessions')
    op.drop_table('questions')
    op.drop_index('ix_user_pairs_match', table_name='matches')
    op.drop_table('matches')
    op.drop_table('users')
    op.drop_table('questions_families')
    # ### end Alembic commands ###
